#!/usr/bin/env python3.7

first_name = "Anand"
last_name = "Murugan"
age = 90
birth_date = "1990/01/01"

print('My name is %s %s' % (first_name, last_name))
print(f'I was born on {birth_date}, and I\'m {age} years old')
